[package]
name = "soltoss-solve"
version = "1.0.0"
edition = "2021"

[dependencies]
borsh = "1.5.7"
borsh-derive = "1.5.7"
solana-program = "=2.2.1"
soltoss = { version = "1.0.0", path = "../program", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
